### PR TITLE
Replaced torch.norm to torch.linalg.norm to attempt to fix issue #77

### PR DESCRIPTION
**Pull request by joneseth1**
# Modulus Pull Request

## Description
Replaced torch.norm to torch.linalg.norm to attempt to fix issue #77. Created multiple commits since I forgot to pip install 'pre-commit' so for the confusion.

### CODE REVIEW

**Review by akshaysubr — APPROVED** [review]
Thanks for the PR @joneseth1. This change looks good to me. Only question I have is if you've run this case with the fix on your end?

**Comment by mnabian** [comment]
Thanks for the PR @joneseth1! Your changes look good to me but the format test for `utils.py` fails. Please run `black .` in the `modulus-launch` directory and push again.

**Comment by joneseth1** [comment]
Ran 'black . ' in 'modulus-launch' and pushed. Let me know if there is anything else. Thanks so much for helping me out with my first open-source PR guys!

**Review by mnabian — APPROVED** [review]

**Pull request merged**
