### PR TITLE
Update SFNO Recipe to align with updated SFNO model in modulus

### PR DESCRIPTION
**Pull request by daviddpruitt**
# Modulus Pull Request

## Description
Updates the SFNO training and inference recipes to align with updated SFNO model

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

## Dependencies

No new dependiencies.

### CODE REVIEW

**Comment by mnabian** [comment]
@daviddpruitt Should we update the configs as well to include the best configs?

**Comment by daviddpruitt** [comment]
@mnabian That's a good idea. We'll need to check with NVR to see what the current best is.

**Comment by mnabian** [comment]
Closing as SFNO recipe will be updated in another PR: https://github.com/NVIDIA/modulus/pull/232

**Pull request closed without merging**
