### PR TITLE
Datapipe Benchmarks

### PR DESCRIPTION
**Pull request by loliverhennigh**
# Modulus Pull Request

Related to issue here https://github.com/NVIDIA/modulus-launch/issues/117

## Description
Implement datapipe benchmarks as an example that is easy for users to run. This will both allow us to show new users a compelling reason to use modulus while also allowing us to iterate on datapipe ideas such as zarr stores.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

### CODE REVIEW

**Review by akshaysubr — APPROVED** [review]

**Comment by NickGeneva** [comment]
Closing since PR should move to core repo.

**Pull request closed without merging**
